### ISSUE TITLE
Option for Saturation in Device

### ISSUE THREAD

**Issue by poudenes** [galinette2000/espmilighthub-domoticz#3]
Will it be possible to control saturation in device module? You can select color, kelvin, brightness, but no saturation.

**Comment by etsach** [comment]
Technically it's not a problem for me to send a saturation command, but the problem is there is no saturation contol in the Domoticz RGB lights interface (and no dzVent command). We should ask this to the Domoticz folks.
However, if you add yourself a saturation virtual device (with a slider), computing RGB from Hue/Saturation is quite simple

**Comment by poudenes** [comment]
I think its better to ask the Domoticz guys if they can implement this.... Would be much nicer then a dummy slider solution :D
